#!/bin/bash

function help(){
    echo "Use getns with restype and resname for ex getns pod pod-0"
    exit 1
}

if [ $# -ne 2 ]
then
    help
fi

# check if kubectl is available
kubectl get $1 --all-namespaces  -ojsonpath="{.items[?(@.metadata.name=='$2')].metadata.namespace}"